### PR TITLE
pimpl error with linker

### PR DESCRIPTION
**Pull request by coax1d**
Cant seem to see the error here does anything jump out of you that seems wrong?

### CODE REVIEW

**Comment by MichaelCook** [comment]
What error are you seeing?
Don't know what I'm looking for...

**Review by MichaelCook — COMMENTED** [review]
You probably don't need any of these destructors - they don't do anything

**Comment by coax1d** [comment]
> What error are you seeing?
> Don't know what I'm looking for...

image

**Comment by coax1d** [comment]
> You probably don't need any of these destructors - they don't do anything

**Comment by coax1d** [comment]
> You probably don't need any of these destructors - they don't do anything

I added some code isolating the issue I am seeing which is that the constructor doesn't seem to work. i.e.
BaseballPlayer player("Michael") --> This does not construct a BaseballPlayer object which has a name 'player.get_name()' returns the empty string

player.has_baseball() does return false (which is accurate)

'player.set_name("Michael")' works correctly

something is up with one of the constructors.

**Comment by coax1d** [comment]
> What error are you seeing?
> Don't know what I'm looking for...

I added some code isolating the issue I am seeing which is that the constructor doesn't seem to work. i.e.
BaseballPlayer player("Michael") --> This does not construct a BaseballPlayer object which has a name 'player.get_name()' returns the empty string

player.has_baseball() does return false (which is accurate)

'player.set_name("Michael")' works correctly

something is up with one of the constructors.

**Pull request merged**
